name: build
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  lint-redcap-fastcgi-client:
    name: lint-redcap-fastcgi-client
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./fastcgi-client/Dockerfile
          override-info: DL3008,DL3018,DL3041,SC2046
          failure-threshold: warning

  scan-redcap-fastcgi-client:
    name: scan-redcap-fastcgi-client
    needs: lint-redcap-fastcgi-client
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build container from Dockerfile
        run: docker build -t ghcr.io/aphp/redcap-fastcgi-client:${{ github.sha }} ./fastcgi-client
      - name: Run Dockle
        uses: erzz/dockle-action@v1.4.0
        with:
          image: ghcr.io/aphp/redcap-fastcgi-client:${{ github.sha }}
          report-format: json
          failure-threshold: fatal
          exit-code: 1
      - name: Scan container for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/aphp/redcap-fastcgi-client:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          scanners: 'vuln,secret,license'
          vuln-type: 'os,library'
          severity: 'CRITICAL'

  push-redcap-fastcgi-client:
    name: push-redcap-fastcgi-client
    needs: scan-redcap-fastcgi-client
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: "{{defaultContext}}:fastcgi-client"
          push: true
          tags: ghcr.io/aphp/redcap-fastcgi-client:${{ github.sha }}
