name: redcap-php-fpm-container-ci
run-name: PHP/FPM CI triggered by @${{ github.actor }}

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  aphp-container-ci-workflow:
    uses: aphp/ci-workflows/.github/workflows/container-ci.yml@main
    with:
      dockerfile-path: "php-fpm/Dockerfile"
      image-name: "ghcr.io/aphp/redcap-php-fpm"