name: fastcgi-client

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  call-aphp-container-ci-workflow:
    uses: aphp/ci-workflows/.github/workflows/container-ci.yml@dev
    with:
      dockerfile-context: "./fastcgi-client"
      dockerfile-name: "Dockerfile"
      image-name: "redcap-fastcgi-client"