name: redcap-htpd-shibd-container-ci
run-name: HTTPD-SHIBD CI triggered by @${{ github.actor }}

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  aphp-container-ci-workflow:
    uses: aphp/ci-workflows/.github/workflows/container-ci.yml@main
    with:
      dockerfile-path: "httpd-shibd/Dockerfile"
      image-name: "ghcr.io/aphp/redcap-httpd-shibd"