name: build

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  call-aphp-container-ci-workflow:
    uses: aphp/ci-workflows/workflows/containers/container-ci.yaml@dev
    with:
      dockerfile-context: "./httpd-shibd"
      dockerfile-name: "./httpd-shibd/Dockerfile"
      image-name: "redcap-httpd-shibd"