name: redcap-fastcgi-client-container-c
run-name: APHP Container CLI Workflow triggered by @${{ github.actor }}

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  call-aphp-container-ci-workflow:
    uses: aphp/ci-workflows/.github/workflows/container-ci.yml@dev
    with:
      dockerfile-context: "./fastcgi-client"
      dockerfile-name: "Dockerfile"
      image-name: "ghcr.io/aphp/redcap-fastcgi-client"